### PR TITLE
Added share dialog and sign in page exercises

### PR DESCRIPTION
**Pull request by tandrews2**
Added two interview question exercises to the repo:

1. Interactive sign in page
2. Share dialog

The next step is to link these exercises into the Github page site for this repo.

### CODE REVIEW

**Review by jramsley — CHANGES_REQUESTED** [review]
Remove the svg sprite in Sign in page.htm

**Review by jramsley — CHANGES_REQUESTED** [review]
Any of the html attributes that start with `ng-` are angular specific bindings and aren't used here.  We should remove them from the html.

**Review by jramsley — COMMENTED** [review]
We could probably slim down newton.css by ~99%.  We should just look for the used classes in `Sign in page.htm` and remove the rest from the css.

**Review by rbaek-onshape — COMMENTED** [review]
Adding onto Jake's comment, we could probably comment out or delete the unused lines in both css files.

**Comment by tandrews2** [comment]
Please see the attached screenshot and video:

sign in page

https://user-images.githubusercontent.com/19534247/110039883-e2eb8780-7d0f-11eb-8a5a-c3cd99afe620.mp4

**Review by jramsley — APPROVED** [review]

**Pull request merged**
